### ISSUE TITLE
Non-Artemis Websites

### ISSUE THREAD

**Issue by CommanderStorm** [ls1intum/Orion#13]
### Describe the bug

The Opening of an Bitbucket Link (through the yellow marked Button Lösungsvorschlag) is
- a one-way street
- Soft-Crashes something in the Background

#### To Reproduce

1. Go to any P-Type Challange of PgDP
2. Click on "Lösungsvorschlag"

#### Expected behavior

The Link schould either not be displayed at all (;D), there should be a way to get back to artemis.
One way to realise this would be is through the Actions-Menu (i.e. a Artemis Tab in the Top with an Option "Go Back to Artemis", that 'Links' back to the Atremis-Main Page)

#### Screenshots

![Bitbucket](https://user-images.githubusercontent.com/26258709/69620232-4e3ea800-103d-11ea-973e-1ac73f8c40aa.PNG)
![Bitbucket_Open](https://user-images.githubusercontent.com/26258709/69620234-4ed73e80-103d-11ea-93c4-d529eb45e51b.PNG)

### Environment

<details><pre>
 - OS: Windows 10
 - IntelliJ 2019.2
 - Browser Chrome
 - Orion-Version 0.2.4
</pre></details>

#### Output in IntelliJ

<details><pre>
netscape.javascript.JSException: TypeError: undefined is not an object
	at javafx.web/com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:157)
	at javafx.web/com.sun.webkit.WebPage.twkExecuteScript(Native Method)
	at javafx.web/com.sun.webkit.WebPage.executeScript(WebPage.java:1511)
	at javafx.web/javafx.scene.web.WebEngine.executeScript(WebEngine.java:973)
	at de.tum.www1.orion.bridge.ArtemisJSBridge.lambda$onOpenedExercise$1(ArtemisJSBridge.java:78)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$9(PlatformImpl.java:418)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:417)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:175)
	at java.base/java.lang.Thread.run(Thread.java:834)
</pre></details>

**Comment by CommanderStorm** [comment]
Okay.. I found the Back-Button, but TBH, the leftclick navigation is not terribly user friendly/intuetive

**Comment by ungaralex** [comment]
Thanks for the suggestion. Good point, I will restrict access to Artemis URLs since it is not really intended to be able to navigate to other websites.
