### ISSUE TITLE
Open in IntelliJ does not work (as Editor)

### ISSUE THREAD

**Issue by florian-glombik** [ls1intum/Orion#40]
### Describe the bug

The _Open in IntelliJ_ functionality does not work.

#### To Reproduce

1. Start Orion with gradle _runIDE_
2. Log in as editor in a course
3. Try to start working on this exercise from the student view
4. _Open in IntelliJ_ does not work
5. See that a JsonSyntaxException is thrown

#### Expected behavior

Clicking _Open in IntellJ_ should open the project in the IDE

#### Screenshots

Button does not work:
![ReviewPR39OrionUpdateDependencies](https://user-images.githubusercontent.com/63976129/117161857-8c0f3680-adc2-11eb-8e0b-10f282104eec.gif)

### Environment

<details><pre>
 - OS: Windows 10
 - IntelliJ 2021.1
 - Browser Chrome 90.0.4430.93
 - Orion Version: 1.1.1
</pre></details>

#### Output in IntelliJ

<details><pre>
Exception in thread "Thread-13730" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 3960 path $.categories[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at de.tum.www1.orion.connector.ide.exercise.OrionExerciseConnector.importParticipation(OrionExerciseConnector.kt:76)
	at de.tum.www1.orion.connector.ide.exercise.OrionExerciseConnector$initializeHandlers$1.onQuery(OrionExerciseConnector.kt:43)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 3960 path $.categories[0]
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402)
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 6 more
</pre></details>

**Comment by MDK5** [comment]
Addtional info:
The issue seems to be limited to the EIST-course and could not be reproduced outside of it yet.
